### PR TITLE
Release 2023-01-25

### PR DESCRIPTION
**Pull request by noatamir**
Merge `develop` into `main`

### CODE REVIEW

**Comment by gabalafou** [comment]
I scanned the pages at the following blog slugs ever so briefly:

- [labs-status-update-may](https://labs-git-release-23-01-25-quansight.vercel.app/blog/labs-status-update-may)
- [quansight-at-scipy2019](https://labs-git-release-23-01-25-quansight.vercel.app/blog/quansight-at-scipy2019)
- [labs-dask-update](https://labs-git-release-23-01-25-quansight.vercel.app/blog/labs-dask-update)
- [whats-new-in-sympy-14](https://labs-git-release-23-01-25-quansight.vercel.app/blog/whats-new-in-sympy-14)
- [joining_labs](https://labs-git-release-23-01-25-quansight.vercel.app/blog/joining_labs)
- [spyder-40-beta4-kite-integration-is-here](https://labs-git-release-23-01-25-quansight.vercel.app/blog/spyder-40-beta4-kite-integration-is-here)
- [quansight-labs-work-update-for-september-2019](https://labs-git-release-23-01-25-quansight.vercel.app/blog/quansight-labs-work-update-for-september-2019)
- [files-improvements](https://labs-git-release-23-01-25-quansight.vercel.app/blog/files-improvements)
- [uarray-attempting-to-move-the-ecosystem-forward](https://labs-git-release-23-01-25-quansight.vercel.app/blog/uarray-attempting-to-move-the-ecosystem-forward)
- [tdk-partners-with-quansight-labs](https://labs-git-release-23-01-25-quansight.vercel.app/blog/tdk-partners-with-quansight-labs)
- [pytorch-tensoriterator-internals-update](https://labs-git-release-23-01-25-quansight.vercel.app/blog/pytorch-tensoriterator-internals-update)
- [introducing-code-generator-v020](https://labs-git-release-23-01-25-quansight.vercel.app/blog/introducing-code-generator-v020)
- [not-a-checklist](https://labs-git-release-23-01-25-quansight.vercel.app/blog/not-a-checklist)
- [Spyder4-variable-explorer](https://labs-git-release-23-01-25-quansight.vercel.app/blog/Spyder4-variable-explorer)
- [low-code-workshop](https://labs-git-release-23-01-25-quansight.vercel.app/blog/low-code-workshop)
- [a-step-towards-educating-with-spyder](https://labs-git-release-23-01-25-quansight.vercel.app/blog/a-step-towards-educating-with-spyder)

Nothing popped out at me on those pages, other than some [missing](https://labs-git-release-23-01-25-quansight.vercel.app/blog/labs-dask-update) [avatars](https://labs-git-release-23-01-25-quansight.vercel.app/blog/a-step-towards-educating-with-spyder), which is to be expected I think. (Although our default no-avatar icons could be improved, I think; something is off, they don't look right to me, they look glitchy-like.)

A few other things I noticed:

- One of the blog slugs uses an underscore rather than a hyphen: joining_labs
- One of the blog slugs uses a capital letter (note that our URLs are case sensitive): Spyder4-variable-explorer
- Some of the blog slugs (files-improvements) are more generic than I would like

**Review by gabalafou — APPROVED** [review]
But I don't

**Comment by bskinn** [comment]
> A few other things I noticed:
> 
> * One of the blog slugs uses an underscore rather than a hyphen: joining_labs
> * One of the blog slugs uses a capital letter (note that our URLs are case sensitive): Spyder4-variable-explorer
> * Some of the blog slugs (files-improvements) are more generic than I would like

If we change these, we will want to add redirects from these old slugs to the new versions, to avoid breaking inbound links.

**Comment by noatamir** [comment]
Thanks @gabalafou and @bskinn! 🌷 
I believe so far the blog slugs were kept the same as they were pre-migration. But I like this suggestion. 
I'm merging the release and will start reviewing the blog slugs with this in mind for the next migration batch.

CC @MarsBarLee @pavithraes for transparency on review change. I will open an issue for these fixes and redirects, but it's not urgent.

**Comment by gabalafou** [comment]
> If we change these, we will want to add redirects from these old slugs to the new versions, to avoid breaking inbound links.

But... haven't we already broken the old links by doing away with the /year/month scheme? For example:

- Old: https://labs.quansight.org/blog/2019/08/spyder-40-beta4-kite-integration-is-here
- New: https://labs.quansight.org/blog/spyder-40-beta4-kite-integration-is-here

**Comment by bskinn** [comment]
> But... haven't we already broken the old links by doing away with the /year/month scheme?

Indeed, never mind! I hadn't realized Labs blog had changed slug scheme.

**Pull request merged**
