### PR TITLE
Add content updates to `consulting` CHANGELOG

### PR DESCRIPTION
**Pull request by bskinn**

### CODE REVIEW

**Comment by bskinn** [comment]
@noatamir Please review/approve/merge this content PR for Consulting before tomorrow's deploy. Thanks!

**Comment by noatamir** [comment]
The photo rename looks good. I can't see the before and after of the white stripe mentioned. But if you can confirm it, I am happy to approve as is.

**Comment by bskinn** [comment]
@noatamir -- The flaw is only visible on a sufficiently wide display.

Current `quansight.com` (the white strip on the right edge of the hero image isn't actually visible, due to the "white" hero background variant in use):



With the fixed image and "black" hero background (I'm glad you reviewed this -- turns out I hadn't yet Published the fix in Storyblok!):

**Comment by noatamir** [comment]
Yes, that's what I was looking for and couldn't see in the preview. Thanks for double checking 🙇‍♀️.

**Review by noatamir — APPROVED** [review]

**Pull request merged**
