### PR TITLE
Create blank template

### PR DESCRIPTION
**Pull request by gabalafou**
The current UI nudges people to create bug reports but a lot of the website issues we want to create and track are not bug reports.

### CODE REVIEW

**Comment by trallard** [comment]
We do not need a blank template - instead changing the config for issues and set blank issue to true

**Comment by trallard** [comment]
FYI this is what I was pointing at -https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#configuring-the-template-chooser

So we need to add a `config.yml`

**Review by trallard — CHANGES_REQUESTED** [review]
Please see other comments 😄

**Comment by trallard** [comment]
¯\_(ツ)_/¯

**Comment by gabalafou** [comment]
Superseded by https://github.com/Quansight/Quansight-website/pull/472

**Pull request closed without merging**
