### PR TITLE
[BUG] - External URLs in 'Footer Navigation > Footer Link' components are treated as internal navigation, leading to broken links

### PR DESCRIPTION
**Pull request by kherma**

### CODE REVIEW

**Comment by bskinn** [comment]
This does fix the labs.quansight.com link, @kherma -- but it appears to have broken the line spacing fixes I made in #285.

After fix of #285:

image

After this PR:

image


Perhaps the `pb-5` React class for setting the bottom-padding isn't getting handled properly somewhere down the line?

**Comment by bskinn** [comment]
Ugh. @kherma, this most recent change resurfaced another bug that I've been wrestling with lately, when trying to get all of the LLC blog posts published. Some of the blog posts trigger the following type of error in the Vercel build:

```
Error occurred prerendering page "/post/announcing-qhub". Read more: https://nextjs.org/docs/messages/prerender-error
--
07:28:30.587 | TypeError: Cannot read property 'firstName' of undefined
07:28:30.587 | at /vercel/path0/dist/apps/consulting/.next/server/chunks/629.js:245:141
07:28:30.587 | at Array.map (<anonymous>)
07:28:30.587 | at getBlogArticlesProps (/vercel/path0/dist/apps/consulting/.next/server/chunks/629.js:232:65)
07:28:30.587 | at getLibraryTiles (/vercel/path0/dist/apps/consulting/.next/server/chunks/629.js:299:83)
07:28:30.587 | at getStaticProps (/vercel/path0/dist/apps/consulting/.next/server/pages/post/[slug].js:165:123)
07:28:30.587 | at processTicksAndRejections (internal/process/task_queues.js:95:5)
07:28:30.588 | at async renderToHTML (/vercel/path0/node_modules/next/dist/server/render.js:492:20)
07:28:30.588 | at async /vercel/path0/node_modules/next/dist/export/worker.js:253:36
07:28:30.588 | at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:79:20)
```

The weird thing is, the blog posts that trigger this error, cause this error to occur _on other blog posts_, in addition to themselves. In general, these other blog posts _build just fine_ if the problematic blog posts aren't set as 'published' in Storyblok.

I've done a lot of diagnosing on this, and I'm planning to create another, detailed issue for it, for after launch. I'd "solved" the problem for launch by identifying two problematic posts ("Panel/Holoviews Learning Aid" and "Spatial Filtering at Scale with Dask and Spatialpandas", both by Adam Lewis) and leaving them unpublished. But, if this issue has the potential to ~randomly emerge as we're trying to fix other things, we may need to fix it now.

cc @gabalafou

**Comment by kherma** [comment]
@bskinn Checking it out currently, but first I have to find a way to reproduce it

**Comment by bskinn** [comment]
Actually -- instead of reverting... let's merge this PR with the removed `clsx` import to `develop`, so that these fixes can then be merged into `main`... and then investigate on a different branch.

**Review by mstoczkowski — APPROVED** [review]

**Comment by bskinn** [comment]
@kherma (cc @gabalafou @trallard) I just observed this bug as being nondeterministic:

```
Error occurred prerendering page "/post/announcing-qhub". Read more: https://nextjs.org/docs/messages/prerender-error
--
07:28:30.587 | TypeError: Cannot read property 'firstName' of undefined
```

On two consecutive Vercel deployments, using the same PR branch and (to my knowledge) no changes to LLC blog content in Storyblok, the [first build errored](https://vercel.com/quansight/quansight-consulting-published/8rPM2kuhrHmWihW7FSUuNw5CHebH) and the [second did not](https://vercel.com/quansight/quansight-consulting-published/J6q7MTUSjuPqMdKJMxbDQ4PUcsYW).

Now I'm wondering if this might be caused by something transient/incidental, such as someone saving and/or publishing content in Storyblok while a Vercel deployment is building.

**Pull request merged**
