### PR TITLE
Switch all code blocks to use valid Code Hike languages

### PR DESCRIPTION
**Pull request by bskinn**
[Code Hike code block docs](https://codehike.org/docs/codeblocks)

- Code Hike does not differentiate between flavors of Python formatting. There is only `python` (or `py`)
- C++ is `cpp`

Not sure why we're getting errors for `c` and `rst`, as both of those are declared as supported.

Perhaps we need to update Code Hike?

### CODE REVIEW

**Comment by bskinn** [comment]
Separately, we may want to highlight the available [Code Hike annotation features][annot] in the blog authoring docs.

Some handy capability in there.

[annot]: https://codehike.org/docs/annotations

**Comment by bskinn** [comment]
Updating Code Hike to 0.9.0 addresses the `rst not valid language` complaint, but
it's still complaining about `C`.

Note the capital `C` in the complaints -- may be important.

Is something transforming the ` ```c ` lines (lowercase `c`) in the Markdown source to ` ```C ` (uppercase `C`)?

For an example in code, see the [Ruby-XND post](https://github.com/Quansight/Quansight-website/blob/4825eecc6e0588b6e7e80d1a380d78ccb20cf5e6/apps/labs/posts/ruby-wrappers-for-the-xnd-project.mdx#L159-L163)

**Comment by gabalafou** [comment]
Here's one example

| Before | After |
| ----- | ----- | 
| python-console | py |
| without syntax highlighting in code blocks declared as python-console | with syntax highlighting | 
| https://labs-git-dependabot-npmandyarntypesnode-20101-quansight.vercel.app/blog/sympy-documentation | https://labs-celzhlhay-quansight.vercel.app/blog/sympy-documentation#guide-on-sympy-best-practices |

**Comment by gabalafou** [comment]
Looking at those screenshots I added, jeez we really need to fix the color contrast of our syntax highlighter 🙈

**Comment by bskinn** [comment]
From my local build:

```
info  - Collecting page data
[====] info  - Generating static pages (4/104)[Code Hike warning] C is not a valid language, no syntax highlighting will be applied.
[=== ] info  - Generating static pages (4/104)[Code Hike warning] C is not a valid language, no syntax highlighting will be applied.
[==  ] info  - Generating static pages (4/104)[Code Hike warning] C is not a valid language, no syntax highlighting will be applied.
[=   ] info  - Generating static pages (4/104)[Code Hike warning] C is not a valid language, no syntax highlighting will be applied.
[Code Hike warning] C is not a valid language, no syntax highlighting will be applied.
[    ] info  - Generating static pages (4/104)[Code Hike warning] C is not a valid language, no syntax highlighting will be applied.
[Code Hike warning] C is not a valid language, no syntax highlighting will be applied.
[Code Hike warning] C is not a valid language, no syntax highlighting will be applied.
[Code Hike warning] C is not a valid language, no syntax highlighting will be applied.
[=   ] info  - Generating static pages (4/104)[Code Hike warning] C is not a valid language, no syntax highlighting will be applied.
[Code Hike warning] C is not a valid language, no syntax highlighting will be applied.
[Code Hike warning] C is not a valid language, no syntax highlighting will be applied.
[Code Hike warning] C is not a valid language, no syntax highlighting will be applied.
[==  ] info  - Generating static pages (4/104)[Code Hike warning] C is not a valid language, no syntax highlighting will be applied.
[=== ] info  - Generating static pages (4/104)[Code Hike warning] C is not a valid language, no syntax highlighting will be applied.
[Code Hike warning] C is not a valid language, no syntax highlighting will be applied.
[ ===] info  - Generating static pages (4/104)[Code Hike warning] C is not a valid language, no syntax highlighting will be applied.
[  ==] info  - Generating static pages (4/104)[Code Hike warning] C is not a valid language, no syntax highlighting will be applied.
[    ] info  - Generating static pages (4/104)[Code Hike warning] C is not a valid language, no syntax highlighting will be applied.
```

It looks like there's a page somewhere that defines a code block with capital-`C` language... but I can't for the life of me find it in the repo.

**Comment by bskinn** [comment]
> Looking at those screenshots I added, jeez we really need to fix the color contrast of our syntax highlighter 🙈

@gabalafou Third-party theme, here's [point of import](https://github.com/Quansight/Quansight-website/blob/0183f7ab2b1645ff4a6cc5dc31b526c8440babe6/apps/labs/services/posts/serializePost.ts#L7).

**Comment by bskinn** [comment]
I'm suspecting that the unexplained `C is not a valid language` is coming as a curious side effect of #822.

Thus, I'm reasonably confident that this issue has been fixed for all code blocks actually showing code on the site, and the PR is ready for review. Attn @gabalafou.

**Review by gabalafou — APPROVED** [review]
Thanks for this!

**Pull request merged**
