### PR TITLE
[BLOG] Add pytorch-ignite-distributed

### PR DESCRIPTION
**Pull request by MarsBarLee**
Link to [blog post, successful build](https://labs-git-pytorch-ignite-distributed-quansight.vercel.app/blog/pytorch-ignite-distributed). Link to [blog post on old site](https://labs.quansight.org/blog/2021/06/distributed-made-easy-with-ignite).

## Links to other Quansight blogs:
There is no need to check for Blog2Blog links due to updated website build. 
## Text styling

- [x] The blog is written with [plain language](https://www.plainlanguage.gov/guidelines/) (where relevant).
- [x] If there are headers, they use the proper header tags in order to do so (with only one level-one header).
- [x] All links describe where they link to (for example, check the [Quansight labs website](https://labs.quansight.org/)).
- [x] Any kind of styling that the author uses (for example, bold for emphasis) is consistent throughout the blog.

## Non-text contents

- [x] All content is represented as text (for example, images need alt text and videos need captions or descriptive transcripts).
- [x] If there are emojis, there are not more than three in a row.
- [x] Don't use [flashing gifs or videos](https://www.w3.org/TR/UNDERSTANDING-WCAG20/seizure-does-not-violate.html).
- [x] If it were to be read as plain text, the blog still makes sense and no information is missing.

### CODE REVIEW

**Review by gabalafou — CHANGES_REQUESTED** [review]
This has too many differences from [the original blog post](https://labs-git-pytorch-ignite-distributed-quansight.vercel.app/blog/pytorch-ignite-distributed), in particular the side-by-side images in the original.

**Comment by MarsBarLee** [comment]
Thanks for catching the difference! I see that the images and table of contents were missing. The images were in a HTML table (thus MDX parser problems) and the table of contents was missing in the original ipynb-to-md conversion file.

I've fixed the table and added alt text.

However, I'm now getting the problem `Error occurred prerendering page` and `Error: Export encountered errors on following paths:/blog/[slug]: /blog/pytorch-ignite-distributed`. [Link to full build error](https://vercel.com/quansight/labs/T7JDfRC5VMdWZo4a75Spv7PZoqXj).

Is this error due to problems outside the blog md document?

**Review by gabalafou — APPROVED** [review]
Okay I fixed the build errors and aligned the columns, but I'm still not sure this new version of the blog post matches closely enough the old version (for example, there's no formatting for the "Note" sections).

But I will leave it up to your judgment whether or not this looks good enough now to merge in.

**Comment by MarsBarLee** [comment]
@gabalafou Thanks for fixing the build errors!

Do you know the admonition syntax that this website theme uses? The Notes section uses admonition.

I looked around and it seems like Markdown doesn’t have it’s own admonition syntax. There are some variations or plugins eg [Python-Markdown](https://python-markdown.github.io/extensions/admonition/) uses ``!!!`` and [Docusaurus](https://docusaurus.io/docs/markdown-features/admonitions) uses `:::info`. There's also the possibility of just using HTML.

I tried using `:::info` and HTML admonition syntax, but neither worked.

For now, I’ve formatted the Notes section as bullet points. Since you said to leave it to my judgement, I think I'll merge with bullet points for now.

**Pull request merged**
