### PR TITLE
Style/quan 15 inline code segment

### PR DESCRIPTION
**Pull request by kherma**

### CODE REVIEW

**Comment by bskinn** [comment]
@noatamir @trallard Please review the Labs blog posts at the [build preview](https://labs-git-style-quan-15-inline-code-segment-quansight.vercel.app/blog), and comment on the new inline code formatting.

It looks pretty good to my eye, though the font weight might be a bit heavy.

The purple color also might look a bit too much like a visited link.

**Comment by noatamir** [comment]
I did a couple of side by side comparisons on the CLI blog post. I think it's a bit too big and makes the lines break too early. 

side by side comparison for new inline code font, first example

side by side comparison for new inline code font, second example

**Comment by kherma** [comment]
@noatamir @bskinn 
I thought that by "match to surrounding text" you mean to make is same size... because originally it was 85% of parent's text. So if inline code was in paragraph with font size 16px then the font size of the code is ~13.6px. Now inline code has same size as parent.

Screenshot 2022-10-12 at 18 34 28

**Comment by kherma** [comment]
@bskinn We can use letter-spacing i think: https://developer.mozilla.org/en-US/docs/Web/CSS/letter-spacing

**Comment by bskinn** [comment]
@kherma Don't worry, what you did is great as a first pass. Now that we have an actual example to work with, though, we're seeing things we couldn't anticipate before.

**Comment by kherma** [comment]
@bskinn There is also something like:[ font-kerning](https://developer.mozilla.org/en-US/docs/Web/CSS/font-kerning) I've never used that before but looks good. Okay, so what's next, should I wait for review and merge or you want to work on that one and test options?

**Comment by trallard** [comment]
Re spacing - that is to be expected since the used typeface is a monospaced font where all characters occupy the same space. So modifying the kerning is definitely not something we should look at doing. 

Re weight - I checked in with Kamil and asked to bump to 500 but I have not reviewed the website (only a screenshot).
The main problem here is there is not enough contrast between the surrounding text and the code colour. This is a problem we have noticed elsewhere with our brand colours.
I will have to go back and review these changes again tomorrow when I am back online and propose adjustments

**Comment by bskinn** [comment]
Per Tania, @kherma, please hold on further work with this PR until she provides her requested changes.

In the meantime, as appropriate, please move on to work on the other issues in the sprint. #404 seems the most natural next project to me.

Thanks!

**Comment by trallard** [comment]
@kherma I just had a look at the font and styling - and think the best styling would look like this:

The_evolution_of_the_SciPy_developer_CLI___Labs

- #b2399a (replace the main branding colour with this plum variant which should be good even for folks overriding light with dark background)
- `font-weight: 400`
- sizing should be `95%` of the parent text

**Comment by bskinn** [comment]
@trallard -- IIRC, you said this looks good to you, ready to merge?

**Comment by trallard** [comment]
Yes this can be merged

**Review by bskinn — APPROVED** [review]

**Pull request merged**
