### PR TITLE
[BLOG] Add spyder-terminal

### PR DESCRIPTION
**Pull request by MarsBarLee**
Link to [blog post, successful build](https://labs-git-spyder-terminal-quansight.vercel.app/blog/spyder-terminal).

## Links to other Quansight blogs:
There is no need to check for Blog2Blog links due to updated website build. 
## Text styling

- [x] The blog is written with [plain language](https://www.plainlanguage.gov/guidelines/) (where relevant).
- [x] If there are headers, they use the proper header tags in order to do so (with only one level-one header).
- [x] All links describe where they link to (for example, check the [Quansight labs website](https://labs.quansight.org/)).
- [x] Any kind of styling that the author uses (for example, bold for emphasis) is consistent throughout the blog.

## Non-text contents

- [x] All content is represented as text (for example, images need alt text and videos need captions or descriptive transcripts).
- [x] If there are emojis, there are not more than three in a row.
- [x] Don't use [flashing gifs or videos](https://www.w3.org/TR/UNDERSTANDING-WCAG20/seizure-does-not-violate.html).
- [x] If it were to be read as plain text, the blog still makes sense and no information is missing.

### CODE REVIEW

**Comment by MarsBarLee** [comment]
The feature here is from an image from the blog post but is not resized yet to 391x174 pixels. Should I resize it? Or will this be fine?

image

**Comment by noatamir** [comment]
> Should I resize it? Or will this be fine?

Looks fine to me. Thanks for checking!

**Comment by MarsBarLee** [comment]
@noatamir I've resized the image to 391x174 pixels and this is how it looks on my screen:
image

It seems a little cropped but it is clearer than the original, bigger resolution. Does it look good on your screen?

**Comment by MarsBarLee** [comment]
@gabalafou @trallard I've updated this with Noa's suggestion. It looks ready to merge. Should I go forward with merging PRs that Noa already reviewed and I made small changes for?

**Review by gabalafou — CHANGES_REQUESTED** [review]
Oh wait, actually I'm going to try to tweak the preview image because I think it looks bad

**Comment by gabalafou** [comment]
This is how the feature image looks now.

When blog post is in the first position in the list:

feature image

When blog post is not in first position in the list:



On mobile:



Better don't you think?

**Comment by MarsBarLee** [comment]
@gabalafou That does look better and clearer in those different contexts. Thanks!

**Review by gabalafou — APPROVED** [review]

**Pull request merged**
