### PR TITLE
[MAINT] use SVG for SciPy array API post hero

### PR DESCRIPTION
**Pull request by lucascolley**
Closes https://github.com/Quansight/Quansight-website/issues/786

### CODE REVIEW

**Comment by lucascolley** [comment]
the preview looks good to me :) cc @bskinn 

Are we happy to leave the published date as September 25th? I suppose it doesn't really matter but I could change it here.

**Comment by bskinn** [comment]
Agreed, @lucascolley, that looks much better on mobile!

The pub date is entirely up to you—it will be no problem to update it as part of this PR, and this is definitely a good time to make the fix. Let me know your decision & we'll get this merged.

**Comment by lucascolley** [comment]
@bskinn I've updated it to match the release date 👍

**Review by bskinn — APPROVED** [review]
SVG hero definitely looks better on mobile. Twitter and LinkedIn social card images rendering ok.

Updated pub date looks good.

All set for merge.

**Pull request merged**
