### PR TITLE
Release 2023 07 11

### PR DESCRIPTION
**Pull request by gabalafou**

### CODE REVIEW

**Review by trallard — APPROVED** [review]

**Review by bskinn — APPROVED** [review]
Both blog posts render ok in gallery and individual pages.

Both posts show Labs logo image in preview cards on Twitter and LinkedIn.

The only hitch is stylistic: both posts use the same preview image, so the gallery looks a bit over-heavy with that same image.

image

Not a fatal blocker, so approving. @trallard, do you want to change this before we build to live?

**Comment by gabalafou** [comment]
> The only hitch is stylistic: both posts use the same preview image, so the gallery looks a bit over-heavy with that same image.

This is a longer/bigger issue with the blog gallery. I've raised this before. Do we know if we have an issue tracking this? If not, I'll create one.

**Comment by bskinn** [comment]
#666 is about the philosophy of duplication of the gallery images.

#668 is more logistical: proposing pulling reused images into a common directory, instead of having an independent copy of each image for each blog post that uses it.

**Comment by gabalafou** [comment]
Thanks, @bskinn!

**Pull request merged**
