### PR TITLE
Release 2023-06-01

### PR DESCRIPTION
**Pull request by pavithraes**
Merge `develop` into `main`

### CODE REVIEW

**Comment by pavithraes** [comment]
Besides README and CHANGELOG updates, everything done via Storyblok should be reflected:
- [Labs team page updates](https://github.com/Quansight/Quansight-website/pull/737/commits/341622517e75642488f651f4730c151546b46bac), and 
- [OSS Services page additions across the Consulting website](https://github.com/Quansight/Quansight-website/pull/737/commits/58baa570cb766cf33d65cba71519f4c458dbd677)

**Comment by bskinn** [comment]
Indeed, @pavithraes, another good catch. Fixed in SB, and LGTM in the new preview build.

**Comment by pavithraes** [comment]
Thanks for the quick update, everything looks good to me!

**Comment by bskinn** [comment]
@pavithraes -- I'm not seeing some of the intended changes reflected on the Labs team page. E.g., Noa is still listed; Lysandros and Albert are *not* listed; Guilherme still shows XND.

Did *those* changes not get published?

**Comment by bskinn** [comment]
Very strange, all appears in order in SB on a first glance

**Comment by bskinn** [comment]
🤦 I clicked over to Labs site using the link in the Consulting footer, which of course went to the live Labs site, not the preview. All is indeed well.

**Review by bskinn — APPROVED** [review]
All the planned changes appear to be in place & working. LGTM.

**Pull request merged**
