### PR TITLE
Remove Sass

### PR DESCRIPTION
**Pull request by gabalafou**

### CODE REVIEW

**Comment by gabalafou** [comment]
#481 raised the question of whether this dev dependency is actually used.

**Comment by gabalafou** [comment]
@bskinn, could you approve this one? I'm pretty sure we can merge it. I don't see any Sass used in the repo anywhere (no .scss, no .sass, app uses Tailwind and PostCSS)

**Comment by bskinn** [comment]
Rebased onto `develop` tip to ensure it still builds ok

**Review by bskinn — APPROVED** [review]
Build went ok, preview build seems fine.

LGTM.

**Pull request merged**
