### PR TITLE
Fix/duplicate link on llc library

### PR DESCRIPTION
**Pull request by kherma**

### CODE REVIEW

**Comment by gabalafou** [comment]
@kherma does this fix https://github.com/Quansight/Quansight-website/issues/171?

**Comment by kherma** [comment]
@gabalafou Yes, everything should work fine now. Please double check: [[Preview of changes](https://quansight-consulting-git-fix-duplicate-link-on-d3745a-quansight.vercel.app/library)]

**Review by galdranorn — APPROVED** [review]

**Comment by gabalafou** [comment]
@kherma, sorry! meant to respond to your earlier message. Yes, it looked fixed on the preview url, thanks!

**Comment by bskinn** [comment]
Has this been merged to production (`main`?) yet? I'm still seeing the duplication in Storyblok. Thanks!

**Pull request merged**
