### PR TITLE
first draft of nasa-rose-2020 blog post

### PR DESCRIPTION
**Pull request by mattip**
## Text styling

- [x] The blog is written with [plain language](https://www.plainlanguage.gov/guidelines/) (where relevant).
- [x] If there are headers, they use the proper header tags in order to do so (with only one level-one header).
- [x] All links describe where they link to (for example, check the [Quansight labs website](https://labs.quansight.org/)).
- [x] Any kind of styling that the author uses (for example, bold for emphasis) is consistent throughout the blog.

## Non-text contents

- [ ] All content is represented as text (for example, images need alt text and videos need captions or descriptive transcripts).
- [x] If there are emojis, there are not more than three in a row.
- [x] Don't use [flashing gifs or videos](https://www.w3.org/TR/UNDERSTANDING-WCAG20/seizure-does-not-violate.html).
- [x] If it were to be read as plain text, the blog still makes sense and no information is missing.

A very rough first draft, based on an outline by @rgommers

### CODE REVIEW

**Comment by mattip** [comment]
There must be a way to have the "permission required" gate delay the CI run rather than fail it. I was worried when I got an email about "ci run failed", but now I understand it is about letting the build run.

**Comment by mattip** [comment]
I want to view the blog post locally, so I started to follow the instructions in the README of the website. I sucessfully did `npm install` in `aps/labs`, and then did `npm i vercel`. But I don't understand how I am supposed to interact with vercel. In order to log in (why do I need to log in?) it seems to want my github credentials and to let me allow it to "act on my behalf". I am not interested in allowing a third-party app to "act on my behalf" in all the repos I have access to in order to render a blog post. It seems like a bit too much.

**Comment by rgommers** [comment]
Thanks @mattip! I rebased and fixed the smaller issues I noticed. Integrating the images would be useful. Another thing I can work on is adding more names of people involved and who does what - I think that is needed, and will make the story more engaging as well.




> I want to view the blog post locally, so I started to follow the instructions in the README of the website. I sucessfully did `npm install` in `aps/labs`, and then did `npm i vercel`. But I don't understand how I am supposed to interact with vercel. In order to log in (why do I need to log in?) it seems to want my github credentials and to let me allow it to "act on my behalf". I am not interested in allowing a third-party app to "act on my behalf" in all the repos I have access to in order to render a blog post. It seems like a bit too much.

I had the same issue. I signed up to Vercel with my email address rather than GitHub ID, but the Vercel CLI is still complaining - I need some help here I guess:
```
$ vercel env pull .env
Error! Your codebase isn’t linked to a project on Vercel. Run `vercel link` to begin.

$ vercel link
Vercel CLI 28.2.0
? Set up “~/code/quansight/Quansight-website/apps/labs”? [Y/n] y
? Which scope should contain your project? rgommers-quansightco
? Link to existing project? [y/N] y
? What’s the name of your existing project? Quansight-website
Error! Project not found
? What’s the name of your existing project?
```

@gabalafou any advice here for Matti and me?

**Comment by bskinn** [comment]
@rgommers @mattip You would have to have paid Vercel seats in order to gain any visibility into the website project, unfortunately. Vercel paywalls virtually everything that it doesn't expose into the Github integration.

**Comment by mattip** [comment]
Is there a way to preview a contributed blog post?

**Comment by bskinn** [comment]
@mattip You need to use a branch-and-merge strategy within the website repo, instead of a fork-and-merge from a fork in your personal GitHub.

Vercel's fork protection will only allow preview builds for forks in accounts with active (paid) Vercel seats.

**Comment by bskinn** [comment]
Using branch-and-merge, the Vercel preview builds will fire automatically, and the links to the previews will be injected into the PR conversation.

**Comment by rgommers** [comment]
Ah, that would have been great to know when reading the instructions. The `README` in this repo doesn't mention this and is quite misleading (it tells you to try the paid features, which aren't going to work). @bskinn would you be able to update those instructions?

@mattip maybe resubmit this PR from a branch?

**Comment by mattip** [comment]
Closing in favor of #408. I hope the `develop` branch is locked from unauthorized people pushing directly to it in the non-fork development model.

**Comment by bskinn** [comment]
@rgommers Yes, I can work to update them. There's a big README PR not yet merged (#357) that really should be merged first, to simplify the adds -- I'll work with @gabalafou to expedite that, and then revise per here.

@mattip Yes, PRs to `develop` require a non-PR-author approving review in order to merge.

**Pull request closed without merging**
