### PR TITLE
Nebari Services page

### PR DESCRIPTION
**Pull request by gabalafou**
## Text styling

- [x] The blog is written with [plain language](https://www.plainlanguage.gov/guidelines/) (where relevant).
- [x] If there are headers, they use the proper header tags in order to do so (with only one level-one header).
- [x] All links describe where they link to (for example, check the [Quansight labs website](https://labs.quansight.org/)).
- [x] Any kind of styling that the author uses (for example, bold for emphasis) is consistent throughout the blog.

## Non-text contents

- [x] All content is represented as text (for example, images need alt text and videos need captions or descriptive transcripts).
- [x] If there are emojis, there are not more than three in a row.
- [x] Don't use [flashing gifs or videos](https://www.w3.org/TR/UNDERSTANDING-WCAG20/seizure-does-not-violate.html).
- [x] If it were to be read as plain text, the blog still makes sense and no information is missing.

### CODE REVIEW

**Comment by bskinn** [comment]
@gabalafou CTA button at the top of the page doesn't seem to be populating the contact form

image

**Comment by gabalafou** [comment]
@bskinn probably something to do with the hacky way that I implemented it. Did you cmd/ctr-click on the button? Doesn't work if you do that.

**Comment by bskinn** [comment]
No, simple left click.

I loaded the page again and it's working now... &lt;shrug&gt;!

**Review by bskinn — APPROVED** [review]
Looked through the page, clicked all the links, everything seems working.

Did not do a close copy review, that's already been done.

LGTM.

**Comment by gabalafou** [comment]
Hmm. The only other explanation I can think of (besides some odd bug) is that if you clicked on "Visit Preview" in the table left by the Vercel bot, it takes you to a preview URL in the format: `https://consulting-git-{branch-name}-quansight.vercel.app`. And if you visit that same URL across multiple PR updates, you could get a cached/older version of the page in your browser. 

Best way to avoid that is to do one of the following

- Use the "View depolyment" link at the bottom of the PR
- Follow the "Inspect" link in the Vercel bot table at the top of the PR
- Open browser dev tools, go to network panel, and check the box that says "disable cache", then with dev tools open, refresh the page

**Pull request merged**
