### PR TITLE
[CONS BLOG] Acceleration in Python

### PR DESCRIPTION
**Pull request by bskinn**
## Text styling

- [ ] The blog is written with [plain language](https://www.plainlanguage.gov/guidelines/) (where relevant).
- [x] If there are headers, they use the proper header tags in order to do so (with only one level-one header).
- [x] All links describe where they link to (for example, check the [Quansight labs website](https://labs.quansight.org/)).
- [x] Any kind of styling that the author uses (for example, bold for emphasis) is consistent throughout the blog.

## Non-text contents

- [ ] All content is represented as text (for example, images need alt text and videos need captions or descriptive transcripts).
- [x] If there are emojis, there are not more than three in a row.
- [x] Don't use [flashing gifs or videos](https://www.w3.org/TR/UNDERSTANDING-WCAG20/seizure-does-not-violate.html).
- [ ] If it were to be read as plain text, the blog still makes sense and no information is missing.

### CODE REVIEW

**Comment by ericdatakelly** [comment]
- [ ] Consider adding or removing citations to create consistency.  It's not clear why some are cited and some are not.  We can probably just cite the less commonly known ones.

**Comment by ericdatakelly** [comment]
- [ ] The image is too small.  If the original, high resolution image is still available, we should use that in the post and save the other image as the featured image.  Irina might have an original.

**Comment by ericdatakelly** [comment]
@bskinn this is ready for review.

**Comment by bskinn** [comment]
> * The image is too small.  If the original, high resolution image is still available, we should use that in the post and save the other image as the featured image.  Irina might have an original.

@irinafumarel, do you have the original for [this image from the post](https://consulting-git-cons-blog-accel-in-python-quansight.vercel.app/posts/acceleration-in-python-which-is-right-for-your-project/pythonacc.png)?

**Comment by irinafumarel** [comment]
@bskinn Here is a larger version of the diagram and also the AI file https://drive.google.com/drive/folders/1WHBG5VwbYJqxr2ABwMSJVpDyzKQoqul3?usp=sharing

**Comment by bskinn** [comment]
Great, thanks @irinafumarel!

@ericdatakelly, can you swap in this larger version?

**Comment by ericdatakelly** [comment]
Done.  Thanks @irinafumarel !

**Pull request merged**
