### PR TITLE
Change section order of ColumnArticle at md breakpoint

### PR DESCRIPTION
**Pull request by gabalafou**
Short-term fix for #452.

### CODE REVIEW

**Comment by gabalafou** [comment]
## Testing 

We need to examine all of the places that the `Column Article` block is being used on the websites. 

It's a shared component so it could be used on both Consulting and Labs. I'm not sure where or if it's being used on the Consulting site.

**Comment by noatamir** [comment]
LGTM for Labs. Thanks for the quick fix!  🌟

**Review by bskinn — APPROVED** [review]
I checked, and currently ColumnArticie is **not used** anywhere I could find on `consulting`.

All OK from a LLC interaction standpoint.

I *did not review* from a code correctness standpoint.

**Review by trallard — APPROVED** [review]
LGTM - so approving

**Pull request merged**
